// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH94O9vWeKDYvm1aeUS8b5Q_gHU41fw6c',
    appId: '1:684274740573:web:71a8b2a106e689e3210cb4',
    messagingSenderId: '684274740573',
    projectId: 'palaconect',
    authDomain: 'palaconect.firebaseapp.com',
    storageBucket: 'palaconect.firebasestorage.app',
    measurementId: 'G-QJ8KVDVQJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiDEIvRdQJOoSiZ3ruTYf8T0tN63RvO5U',
    appId: '1:684274740573:android:6f9d185fbca076af210cb4',
    messagingSenderId: '684274740573',
    projectId: 'palaconect',
    storageBucket: 'palaconect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRduwL3b8pRF0DqEQouBEFUuLdXFKUu28',
    appId: '1:684274740573:ios:917225e875f64b9d210cb4',
    messagingSenderId: '684274740573',
    projectId: 'palaconect',
    storageBucket: 'palaconect.firebasestorage.app',
    iosBundleId: 'com.example.palaconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRduwL3b8pRF0DqEQouBEFUuLdXFKUu28',
    appId: '1:684274740573:ios:917225e875f64b9d210cb4',
    messagingSenderId: '684274740573',
    projectId: 'palaconect',
    storageBucket: 'palaconect.firebasestorage.app',
    iosBundleId: 'com.example.palaconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH94O9vWeKDYvm1aeUS8b5Q_gHU41fw6c',
    appId: '1:684274740573:web:5b4a18512e545d89210cb4',
    messagingSenderId: '684274740573',
    projectId: 'palaconect',
    authDomain: 'palaconect.firebaseapp.com',
    storageBucket: 'palaconect.firebasestorage.app',
    measurementId: 'G-XDXP8GKPKV',
  );

}